codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: "0...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "thirdparty/ctest.h"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

curl -X POST --data-binary @codecov.yml https://codecov.io/validate
